### ISSUE TITLE
Spawning in Hobbit sometimes creates a villager instead, and causes an error

### ISSUE THREAD

**Issue by BugmanBugman** [brandon3055/Tolkien-Tweaks#4]
https://paste.dimdev.org/awijodiyag.mccrash

**Comment by GreatOrator** [comment]
This should actually be posted at the tolkienmobs mod page https://github.com/GreatOrator/TolkienTweaks-Mobs/issues

Also, can you provide more details...other mods installed or modpack being used, etc.
